config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users

    root 'welcome#home'    
  
    resources :projects do
      member do
        get :delete
      end
    end

    resources :providers do
      member do
        get :delete
      end
    end

  
    

end

app/models/provider.rb
class Provider < ActiveRecord::Base
has_and_belongs_to_many :onboardings
has_and_belongs_to_many :users
   
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  def index    
    @current_user =User.find(current_user.id)
    @providers = @current_user.providers
  end

  def show
    @current_user =User.find(current_user.id)
    @providers = @current_user.providers
    @provider = @providers.find(params[:id])

  end

  def new
    @provider = Provider.new()
  end

  def create
    @provider = Provider.new(provider_params)
    if @provider.save
      @current_user =User.find(current_user.id)
      @current_user.providers << @provider                         #Adding the provider to the user on the table many to many
      flash[:notice] = "Provider was successfully created"
      redirect_to(providers_path)
    else
      render('new')
    end
  end

  def edit
    @current_user =User.find(current_user.id)
    @providers = @current_user.providers
    @provider = @providers.find(params[:id])

  end

  def update
    @current_user =User.find(current_user.id)
    @providers = @current_user.providers
    @provider = @providers.find(params[:id])

    if @provider.update_attributes(provider_params)
      flash[:notice] = "Provider was successfully updated"
      redirect_to(provider_path(@provider))    
    else
      render('edit')
    end
  end

  def delete
    @current_user =User.find(current_user.id)
    @providers = @current_user.providers
    @provider = @providers.find(params[:id])

  end

  def destroy
    @current_user =User.find(current_user.id)
    @providers = @current_user.providers
    @provider = @providers.find(params[:id])

    @provider.destroy
    flash[:notice] = "Provider [ '#{@provider.name}' ] was successfully deleted"
    redirect_to(providers_path)
  end

  private
  def provider_params
    params.require(:provider).permit(:name)
  end
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/providers/delete.html.erb
<%= form_for(@provider, :method => 'delete') do |f| %>
    
    <h1>Are you sure?</h1>
    <h4> You area about to delete the record </h4>
    <h4><strong><%= @provider.name %></strong><h4>
    <div class="form-buttons">
        <%= f.submit("Delete Provider")%>
    <div>

<% end %>

app/views/providers/edit.html.erb
<h1>Update provider</h1>
<%= form_for(@provider) do |f| %>
<table summary='Project form field'>
<tr>
    <th>Name</th>
    <td><%= f.text_area(:name)%></td>
</tr>
<tr>
  <td>
    <div class="form-buttons">
      <%= f.submit('Update provider') %>
    </div>
  </td>
</tr>
</table>
<% end %>

app/views/providers/index.html.erb
<% if !flash[:notice].blank? %>
    <div class="notice">
    <%= flash[:notice]%>
    </div>
<%end%>
<div class='content'>
    <div class='titles'>
    <h4>Providers</h4>
    </div>
    <%= link_to 'Create new provider' ,new_provider_path %>
    <br>
    <table>
    <tr>
    <th>ID</th>
    <th>Name</th>
    </tr>
    <% @providers.each do |provider|%>
    <tr>
    <td><%= provider.id%></td>
    <td><%= provider.name%></td>
    <td>
    <%= link_to 'Show', provider_path(provider) %>
    <%= link_to 'Edit', edit_provider_path(provider) %>
    <%= link_to 'Delete', delete_provider_path(provider) %>
    </td>
    <% end %>
    </tr>
    </table>

</div>

app/views/providers/new.html.erb
<h1> CREATE PROVIDER </h1>
<%= form_for(@provider) do |f| %>
<table summary='Project form field'>
<tr>
    <th>Name</th>
    <td><%= f.text_area(:name)%></td>
</tr>
<tr>
  <td>
    <div class="form-buttons">
      <%= f.submit('Create provider') %>
    </div>
  </td>
</tr>
</table>
<% end %>

app/views/providers/show.html.erb
<% if !flash[:notice].blank? %>
<div class="notice">
<%= flash[:notice]%>
</div>
<%end%>

<h1>SHOW PROVIDERS</h1>
<ul>
<li>Id : <%= @provider.id%></li>
<li>Name : <%= @provider.name%></li>
</ul>