config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users

    root 'welcome#home'    
  
    resources :projects do
      member do
        get :delete
      end
    end

    resources :providers do
      member do
        get :delete
      end
    end

  
    

end

app/models/project.rb
class Project < ActiveRecord::Base
    belongs_to :user
    has_many :projects
    has_and_belongs_to_many :questions
    accepts_nested_attributes_for :questions, reject_if: :all_blank, allow_destroy: true
    mount_uploader :cover, CoverUploader
    

    scope :where_user_id, lambda {|query| where(["user_id LIKE ?","%#{query}%"])}
    scope :sorted, lambda {order('id DESC')}
   
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  def index
    @projects = Project.where_user_id(current_user.id)
    
  end

  def show
    @project = Project.find(params[:id])
    #Todos los proveedores que estan dados de alta en ese proyecto
    
  end

  def new
    @project = Project.new({:user_id => current_user.id})
    #Todos los proveedores que estan dados de alta
    @current_user =User.find(current_user.id)
    
   
  end

  def create
    #Instantiate a new object using form parameters
    @project = Project.new(project_params)
    #Save the object
    if @project.save
      flash[:notice]="Project created successfully"
      redirect_to(projects_path)
    else
      render('new')
    end

  end

  def edit
    @project = Project.find(params[:id])
    #Todos los proveedores que estan dados de alta
    @current_user =User.find(current_user.id)
    
  end

  def update
    @project = Project.find(params[:id])  

    if @project.update_attributes(project_params)
      flash[:notice]="Project updated successfully."
      redirect_to(project_path(@project))
    else
      render('edit')
    end
  end

  def delete
    @project =Project.find(params[:id])
  end

  def destroy
    @project =Project.find(params[:id])
    @project.destroy
    flash[:notice]="Project [ '#{@project.name}' ] destroyed successfully."
    redirect_to(projects_path)
  end




  private
  def project_params
    params.require(:project).permit(:name,:description,:sent_at,:cover,:user_id,questions_attributes: [:id,:title,:_destroy])
  end

 


end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_question_fields.html.erb
<div class='nested-fields sis'>
    <%= f.label 'Question' %>
    <%= f.input_field :title %>
    <%= link_to_remove_association "Remove question", f , class: 'btn btn-default form-button'%>

</div>

app/views/projects/delete.html.erb
<%= form_for(@project, :method => 'delete') do |f| %>
    
    <h1>Are you sure?</h1>
    <h4> You area about to delete the record </h4>
    <h4><strong><%= @project.name %></strong><h4>
    <div class="form-buttons">
        <%= f.submit("Delete Project")%>
    <div>

<% end %>

app/views/projects/edit.html.erb
<h1>UPDATE A PROJECT</h1>
<%= simple_form_for @project do |f|%>
    <table summary='Project form fields'>
    <tr>
     <th>Name : </th>
     <td><%= f.input_field(:name)%></td>
    </tr>
    
    <tr>
    <th>Description : </th>
    <td><%= f.input_field(:description)%></td>
   </tr>


   <tr>
   <th>Cover Image : </th>
   <td><%= f.input_field :cover, :as => :file%></td>  
  </tr>

   <%= f.input_field(:user_id, class: 'esconder')%>

    
    </table>

   <%= f.simple_fields_for :questions do |question|%>
     <%= question.input :title%>
   <% end %>
    <div class='links'>
    <%= link_to_add_association 'Add question', f ,:questions, class: "btn btn-outline-info"%>
    </div>


 
   <div class="form-buttons">
   <%= f.submit('Update project') %>
   </div>

<% end %>

app/views/projects/index.html.erb
<% if !flash[:notice].blank? %>
<div class="notice">
<%= flash[:notice]%>
</div>
<%end%>
<div class='content'>
    <div class='titles'>
    <h4>My templates</h4>
    </div>
    <div>
    <table>
        
    <%= link_to 'NEW PROJECT', new_project_path , class:'btn btn-outline-info '%>
    <tr>
    
    <th>Id</th>
    <th>Name</th>
    <th>Description</th>
    <th>Sent at</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th>Users ID (FK)</th>
    </tr>
    <% @projects.each do |project| %>
    <tr>
    <td><%= project.id %></td>
    <td><%= project.name %></td>
    <td><%= project.description %></td>
    <td><%= project.sent_at ? 'Yes' : 'No' %></td>
    <td><%= project.created_at %></td>
    <td><%= project.updated_at %></td>
    <td><%= project.user_id %></td>    
    <td>
    <%= link_to 'Show', project_path(project) %>
    <%= link_to 'Edit', edit_project_path(project) %>
    <%= link_to 'Delete', delete_project_path(project) %>
    </td>
    </tr>
    <% end %>

    </table>
    </div>
</div>

app/views/projects/new.html.erb
<h1> CREATE A NEW PROJECT </h1>

<%= simple_form_for @project do |f|%>
    <table summary='Project form fields'>
    <tr>
     <th>Name : </th>
     <td><%= f.input_field(:name)%></td>
    </tr>
    
    <tr>
    <th>Description : </th>
    <td><%= f.input_field(:description)%></td>
   </tr>

   <tr>
   <th>Cover Image : </th>
   <td><%= f.input_field :cover, :as => :file %></td>  
  </tr>

   <%= f.input_field(:user_id, class: 'esconder')%>
   <%= @categ %>
   
    </table>

    <%= f.simple_fields_for :questions do |question| %>
        <%= question.input :title%>     
    <% end %>
    <div class='links'>
        <%= link_to_add_association 'Add question', f, :questions, class: "btn btn-outline-info" %>
    </div>

  
    <div class="form-buttons">
    <%= f.submit 'Create project' %>
    </div>

<%end%>

app/views/projects/show.html.erb
<html>
<body>
<% if !flash[:notice].blank? %>
<div class="notice">
<%= flash[:notice]%>
</div>
<%end%>
 <h2>PROJECT : <%= @project.name%> </h2>
    <ul>
    <li>Name : <%= @project.name%></li>
    <li>Description : <%= @project.description%></li>
    <li>Sent : <%= @project.sent_at ? 'Yes' : 'No' %> </li>
    <li>Created at : <%= @project.created_at %></li>
    <li>Updated at : <%= @project.updated_at %></li>
    <li>Creator user : <%= @project.user_id %></li>
    </ul>
    <div class='polaroid'>
        <%= image_tag @project.cover.url  if @project.cover? %>
        <div class='container'>
        <p>Template : <%= @project.name%></p>
    </div>
    
    
</body>
</html>