config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users

    root 'welcome#home'    
  
    resources :projects do
      member do
        get :delete
      end
    end

    resources :providers do
      member do
        get :delete
      end
    end

  
    

end

app/views/layouts/_messages.html.erb
<!DOCTYPE html>
<html>
<head></head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<p class="navbar-text pull-right">
<% if user_signed_in? %>    
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>


</body>
</html>

app/views/layouts/_navbar_logged.html.erb
<!DOCTYPE html>
<html>
<head></head>
<body>
<nav class="navbar navbar-expand-sm bg-info navbar-dark">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <%= link_to "Home", root_path, class:'nav-link'%>
    </li>
    <li class="nav-item">      
      <%= link_to("My templates",projects_path, class: "nav-link")%> 
    </li>
    <li class="nav-item">
      <%= link_to("Providers",providers_path,class: "nav-link" )%>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Records</a>
    </li>
    <li>
    <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= current_user.first_name%>
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <%= link_to "Edit profile", edit_user_registration_path, class:'dropdown-item' %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class:'dropdown-item' %>
    </div>
    </div>
    </li>
  </ul>
</nav>

</body>
</html>

app/views/layouts/_navbar_notlogged.html.erb
<!DOCTYPE html>
<html>
<head></head>
<body>
<nav class="navbar navbar-expand-sm bg-info navbar-dark">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <%= link_to "Home", root_path, class:'nav-link'%>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">About us</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Contact</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Something else</a>
    </li>
    <li class="nav-item">
    <%= link_to "Sign up", new_user_registration_path, class:'nav-link' %>
    </li>
    <li class="nav-item"> 
    <%= link_to "Login", new_user_session_path, class:'nav-link'%>  
    </li>
    
  </ul>
</nav>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Onboarder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in?%>
<%= render 'layouts/navbar_logged' %>
<%else%>
<%= render 'layouts/navbar_notlogged'%>
<%end%>


<%= yield %>

</body>
</html>